language: php
php:
  - 7.4
  - nightly
install:
  - composer self-update
  - composer install --prefer-dist --no-interaction
script:
  - composer cs
  - composer test
cache:
  directories:
    - vendor/
